### PR TITLE
added application info

### PR DESCRIPTION
**Pull request by rotimi-98**
This looks good

### CODE REVIEW

**Comment by rdacggcpuser** [comment]
This looks extremely good

**Review by rdacggcpuser — APPROVED** [review]
Approved

**Review by rdacggcpuser — APPROVED** [review]
Approved

**Review by rotimi-98 — COMMENTED** [review]
Pls approve

**Review by rdacggcpuser — APPROVED** [review]
Looks good

**Review by rdacggcpuser — APPROVED** [review]

**Pull request merged**
